name: Build

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      NUGET_XMLDOC_MODE: skip
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: Install .NET (v5.0)
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.x
      - name: Test
        run: |
          dotnet test --configuration Debug
          dotnet test --configuration Release
      - name: Publish
        run: dotnet publish src/Noted -o src/Noted/bin/Publish/ --configuration Release
      - name: Upload build artifacts (CLI)
        uses: actions/upload-artifact@v1
        with:
          name: Noted
          path: src/Noted/bin/Publish/

  publish:
    if: contains(github.ref, 'tags/v') # only publish tagged versions
    needs: [test]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rid: [win-x64, linux-x64]
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      NUGET_XMLDOC_MODE: skip
    steps:
      - uses: actions/checkout@v1
      - name: Install .NET (v5.0)
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.x
      - name: Extract version
        id: extract_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        shell: bash
      - name: Build
        run: |
          cd ./src/Noted
          dotnet publish -c Release --self-contained false -r ${{ matrix.rid }} -o ./bin/Portable.${{ matrix.rid }}
          dotnet publish -c Release --self-contained -r ${{ matrix.rid }} -o ./bin/${{ matrix.rid }}
          zip -r bin/Noted.${{ env.NOTED_VERSION }}.Portable.${{ matrix.rid }} ./bin/Portable.${{ matrix.rid }}
          zip -r Noted.${{ env.NOTED_VERSION }}.${{ matrix.rid }} ./bin/${{ matrix.rid }}
      - name: Create Release
        uses: ncipollo/release-action@v1.8.4
        with:
          name: Release ${{ env.NOTED_VERSION }}
          body: |
              [Changelog](https://github.com/codito/Noted/blob/master/CHANGELOG.md)
          artifacts: "src/Noted/*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
